# Pre-commit git hooks.
#
# Usage:
#   1. Run one of:
#     $ pip install pre-commit
#     $ brew install pre-commit
#
#   2. Install hooks
#     $ pre-commit install
#
#   3. Optionally, enable automatic updates
#     $ pre-commit autoupdate
repos:
- repo: local
  hooks:
  - id: google-calendar-move-to-date-test
    name: google-calendar-move-to-date-test
    language: script
    files: 'extensions/google_calendar_workflow/js/.*'
    entry: scripts/google_calendar_move_to_date_test.sh
